# Generated by Django 6.0.4 on 2026-04-24 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0001_initial'),
        ('ubicaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ENCENDIDO', 'Encendido'), ('APAGADO', 'Apagado')], max_length=20)),
                ('modo', models.CharField(choices=[('AUTOMATICO', 'Automatico'), ('MANUAL', 'Manual'), ('DISPOSITIVO', 'Decidido por ESP32')], max_length=20)),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_riego', to='iot.actuador')),
            ],
            options={
                'verbose_name': 'estado de riego',
                'verbose_name_plural': 'estados de riego',
                'db_table': 'estado_riego',
                'ordering': ('-fecha_hora_inicio',),
            },
        ),
        migrations.CreateModel(
            name='ReglaRiegoAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('humedad_encendido', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('humedad_apagado', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_riego', to='iot.actuador')),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_riego', to='ubicaciones.parcela')),
                ('sensor_humedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_riego', to='iot.sensor')),
            ],
            options={
                'verbose_name': 'regla de riego automatico',
                'verbose_name_plural': 'reglas de riego automatico',
                'db_table': 'regla_riego_automatico',
            },
        ),
        migrations.CreateModel(
            name='ComandoRiego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comando', models.CharField(choices=[('ENCENDER', 'Encender'), ('APAGAR', 'Apagar'), ('REINICIAR', 'Reiniciar')], max_length=30)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automatico'), ('DISPOSITIVO', 'Decidido por ESP32'), ('SISTEMA', 'Sistema')], max_length=30)),
                ('parametro', models.JSONField(blank=True, null=True)),
                ('fecha_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('estado_comando', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('EJECUTADO', 'Ejecutado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=30)),
                ('actuador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos_riego', to='iot.actuador')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos_riego', to='usuarios.usuarioperfil')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos_riego', to='riego.reglariegoautomatico')),
            ],
            options={
                'verbose_name': 'comando de riego',
                'verbose_name_plural': 'comandos de riego',
                'db_table': 'comando_riego',
                'ordering': ('-fecha_hora_envio',),
            },
        ),
        migrations.CreateModel(
            name='RespuestaComando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=100)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('codigo_error', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora_respuesta', models.DateTimeField(auto_now_add=True)),
                ('comando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='riego.comandoriego')),
            ],
            options={
                'verbose_name': 'respuesta de comando',
                'verbose_name_plural': 'respuestas de comandos',
                'db_table': 'respuesta_comando',
                'ordering': ('-fecha_hora_respuesta',),
            },
        ),
    ]
