# Generated by Django 6.0.4 on 2026-04-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(help_text='Estado del riego (encendido/apagado)')),
                ('modo', models.CharField(choices=[('AUTO', 'Automático'), ('MANUAL', 'Manual')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'verbose_name': 'riego',
                'verbose_name_plural': 'riegos',
            },
        ),
    ]
