# Generated by Django 6.0.4 on 2026-04-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iot', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=80)),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Critica')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('ATENDIDA', 'Atendida'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=30)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('actuador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='iot.actuador')),
                ('atendida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_atendidas', to='usuarios.usuarioperfil')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='iot.nodoiot')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='iot.sensor')),
            ],
            options={
                'verbose_name': 'alerta del sistema',
                'verbose_name_plural': 'alertas del sistema',
                'db_table': 'alerta_sistema',
                'ordering': ('-fecha_hora',),
            },
        ),
        migrations.CreateModel(
            name='AuditoriaSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla_afectada', models.CharField(max_length=80)),
                ('id_registro_afectado', models.PositiveIntegerField(blank=True, null=True)),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('ACTUALIZAR', 'Actualizar'), ('ELIMINAR', 'Eliminar'), ('INICIAR_SESION', 'Iniciar sesion'), ('ENVIAR_COMANDO', 'Enviar comando')], max_length=30)),
                ('descripcion', models.TextField()),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='usuarios.usuarioperfil')),
            ],
            options={
                'verbose_name': 'auditoria del sistema',
                'verbose_name_plural': 'auditorias del sistema',
                'db_table': 'auditoria_sistema',
                'ordering': ('-fecha_hora',),
            },
        ),
    ]
