# Generated by Django 6.0.4 on 2026-04-24 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodoIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_nodo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=150, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento'), ('DESCONECTADO', 'Desconectado')], default='ACTIVO', max_length=30)),
                ('parcela', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodos_iot', to='ubicaciones.parcela')),
            ],
            options={
                'verbose_name': 'nodo IoT',
                'verbose_name_plural': 'nodos IoT',
                'db_table': 'nodo_iot',
            },
        ),
        migrations.CreateModel(
            name='Actuador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_actuador', models.CharField(choices=[('RELE', 'Rele'), ('BOMBA', 'Bomba'), ('VALVULA', 'Valvula'), ('MOTOR', 'Motor')], default='RELE', max_length=50)),
                ('modelo', models.CharField(blank=True, max_length=80, null=True)),
                ('pin_conexion', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_actual', models.CharField(choices=[('ENCENDIDO', 'Encendido'), ('APAGADO', 'Apagado'), ('ERROR', 'Error')], default='APAGADO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], default='ACTIVO', max_length=20)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actuadores', to='iot.nodoiot')),
            ],
            options={
                'verbose_name': 'actuador',
                'verbose_name_plural': 'actuadores',
                'db_table': 'actuador',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_sensor', models.CharField(choices=[('TEMPERATURA', 'Temperatura'), ('HUMEDAD_AMBIENTE', 'Humedad ambiente'), ('HUMEDAD_SUELO', 'Humedad del suelo'), ('LLUVIA', 'Lluvia'), ('LUZ', 'Luz')], max_length=50)),
                ('modelo', models.CharField(default='DHT11', max_length=50)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('pin_conexion', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('DANADO', 'Danado')], default='ACTIVO', max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='iot.nodoiot')),
            ],
            options={
                'verbose_name': 'sensor',
                'verbose_name_plural': 'sensores',
                'db_table': 'sensor',
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('calidad_dato', models.CharField(choices=[('VALIDO', 'Valido'), ('SOSPECHOSO', 'Sospechoso'), ('ERROR', 'Error')], default='VALIDO', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='iot.sensor')),
            ],
            options={
                'verbose_name': 'lectura de sensor',
                'verbose_name_plural': 'lecturas de sensores',
                'db_table': 'lectura_sensor',
                'ordering': ('-fecha_hora',),
            },
        ),
    ]
